name: Publish to Smithery

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish-smithery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      
      - name: Install dependencies
        run: npm install
      
      - name: Create Smithery Package
        run: |
          TEMP_DIR=$(mktemp -d)
          PACKAGE_DIR="$TEMP_DIR/video-analysis-mcp"
          mkdir -p "$PACKAGE_DIR"
          
          # Copy source files (this project doesn't have a build step)
          cp *.js "$PACKAGE_DIR/"
          cp smithery.yaml "$PACKAGE_DIR/"
          cp package.json README.md "$PACKAGE_DIR/"
          if [ -f LICENSE ]; then cp LICENSE "$PACKAGE_DIR/"; fi
          
          # Create Smithery metadata
          cat > "$PACKAGE_DIR/smithery.json" << EOL
          {
            "name": "video-analysis-mcp",
            "version": "$(node -p "require('./package.json').version")",
            "description": "Video Analysis AI Server using Google's Gemini AI",
            "smithery": {
              "displayName": "Video Analysis AI Server",
              "description": "Provide detailed video analysis by leveraging Google's Gemini AI to describe content, identify quality issues, and assess pacing and organization",
              "startCommand": {
                "type": "stdio",
                "command": "node",
                "args": ["mcp-server.js"]
              }
            }
          }
          EOL
          
          cd "$TEMP_DIR"
          tar -czf video-analysis-mcp.tgz video-analysis-mcp
          
          cd "$GITHUB_WORKSPACE"
          mkdir -p artifacts
          mv "$TEMP_DIR/video-analysis-mcp.tgz" artifacts/
          
          rm -rf "$TEMP_DIR"
      
      - name: Install Smithery CLI
        run: npm install -g @smithery/cli
      
      - name: Publish to Smithery
        run: |
          npx @smithery/cli install artifacts/video-analysis-mcp.tgz --id video-analysis-mcp --client claude --key ${{ secrets.SMITHERY_API_KEY }}
          
          if [ $? -ne 0 ]; then
            curl -X POST 'https://api.smithery.ai/v1/teams/default/servers' \
              -H "Authorization: Bearer ${{ secrets.SMITHERY_API_KEY }}" \
              -H 'Content-Type: multipart/form-data' \
              -F "package=@artifacts/video-analysis-mcp.tgz" \
              -F 'id=video-analysis-mcp' \
              -F 'description=Video Analysis AI Server using Google Gemini AI'
          fi